# Area name: Myeong

simulation_area:  # Lower left and upper right positions of the whole area in latitude and longitude
  lower_left:
    lat: 37.55621722652808
    lon: 126.97439866973117
  upper_right:
    lat: 37.571607018927885
    lon: 126.99630266143203

bs:
  # xyz position. Positive x, y, z directions point to east, north, and upward, respectively.
  position: [ [-722, -722, 25], [-417, -824, 27], [-262, -844, 27], [-327, -642, 24], [-537, -648, 25], 
              [-814, -528, 23], [-602, -438, 28], [-442, -420, 52], [-725, -305, 83], [-642, -107, 26],
              [-511, -174, 62], [-693, 22, 110], [-338, -82, 70], [-366, 157, 107], [-654, 312, 50],
              [-660, 753, 98], [-275, 383, 60], [-288, 654, 81], [-516, 541, 70], [-159, -508, 92],
              [18, -471, 36], [-63, -769, 28], [103, -697, 28], [215, -539, 25], [228, -349, 30],
              [-50, -319, 54], [-184, 25, 65], [-3, -171, 78], [163, 55, 30], [-7, 187, 70], 
              [-14, 69, 50], [-294, -255, 72], [-49, 398, 115], [148, 521, 118], [-132, 566, 29], 
              [50, 660, 35], [-26, 728, 39], [693, -821, 26], [945, -738, 29], [659, -390, 48],
              [534, -457, 28], [354, -251, 78], [908, -528, 28], [878, -302, 30], [926, -124, 61],
              [901, 202, 65], [242, 109, 26], [470, 56, 60], [624, -140, 28], [587, 200, 30], 
              [167, 349, 90], [653, 456, 32], [875, 557, 39], [601, 300, 30], [428, 401, 30],
              [363, 301, 58], [632, 590, 28], [493, 515, 28], [384, 650, 45], [284, 551, 26], 
              [175, 667, 37], [342, 747, 29], [621, 785, 34], [707, 695, 26], [573, 693, 26],
              [292, -45, 28], [110, -223, 40], [-77, -70, 25], [-51, -590, 40], [533, -246, 24],
              [-933, -673, 100], [-930, -334, 94], [-883, -76, 105], [-765, 481, 59], [-869, 744, 102] ]

  # Counter-clock wise angle in degree. Antenna array is facing towards x-direction if this value is 0.
  direction: [100, 180, 120, 210, 340, 190, 340, 250, 270, 310,
            220, 190, 330, 90, 90, 240, 0, 90, 90, 290,
            330, 200, 350, 180, 90, 280, 300, 310, 140, 90,
            200, 190, 200, 270, 270, 240, 260, 140, 160, 230,
            230, 270, 180, 120, 180, 180, 220, 90, 140, 50,
            280, 140, 230, 270, 60, 290, 190, 270, 240, 60,
            60, 270, 220, 90, 140, 220, 270, 80, 210, 280,
            320, 300, 60, 0, 270]
  # Downwards tilt angle in degree
  tilt: [11, 11, 11, 10, 11, 10, 12, 19, 29, 11, 
         22, 37, 25, 37, 19, 34, 22, 28, 25, 32,
         14, 12, 12, 11, 12, 20, 23, 27, 12, 25,
         19, 25, 39, 40, 12, 14, 15, 11, 12, 18,
         12, 27, 12, 12, 22, 23, 11, 22, 12, 12,
         31, 13, 15, 12, 12, 21, 12, 12, 17, 11,
         14, 12, 13, 11, 11, 12, 15, 11, 15, 10,
         34, 32, 36, 21, 35]

